### ISSUE TITLE
Potential bug with implementation of half_life in net_loss_exp function

### ISSUE THREAD

**Issue by andrewcglover** [mrc-ide/netz#33]
https://github.com/mrc-ide/netz/blob/ac8cd8a883b8102e737fa156864f74bc54e7b776/R/net_loss.R#L27-L29

I'm not sure if there is a bug here - should the proportion retained instead be calculated from exp(-(log(2) / half_life) * t) , or alternatively from exp(-(1 / mean_life) * t) where mean_life is the mean lifespan of a net, rather than the half-life?

**Comment by pwinskill** [comment]
Hi @andrewcglover 
Apologies for the slow response here. Good spot - this is really a mis-named argument. The confusions arises as we have somewhat mashed together 2 net models here, the one from MAP (`net_loss_map()`) which _is_ parameterised via a half life, and the one consistent with `malariasimulation` which should be parameterised by an argument named `mean_lifespan`. This should be re-named for the next release
